### Получить всех сотрудников
GET http://localhost:8080/employees

### Создать сотрудника
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "Ирина",
  "lastName": "Смирнова",
  "department": 2,
  "salary": 1000
}

### Создать сотрудника 2
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "Андрей",
  "lastName": "Иванов",
  "department": 1,
  "salary": 2000
}

### Получить сумму зарплат
GET http://localhost:8080/employees/salary/sum

### Получение сотрудника с минимальной зарплатой
GET http://localhost:8080/employees/salary/min

### Получение сотрудника с максимальной зарплатой
GET http://localhost:8080/employees/salary/max

### Получение всех сотрудников, зарплата которых больше средней зарплаты
GET http://localhost:8080/employees/high-salary